apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        release: {{ $.Release.Name }}
    spec:
      containers:
      - name: test-api-gw
        image: "s28938/test-api-gw:{{ .Values.image.version }}"
        ports:
        - containerPort: {{ .Values.port }}
